export const INCREAMENT_COUNTER='INCREAMENT_COUNTER'
export const DECREAMENT_COUNTER='DECREAMENT_COUNTER'
export const FACILITIES_DATA='FACILITIES_DATA'
export const REMOVE_DATA='REMOVE_DATA'
export const EDIT_DATA='EDIT_DATA'
export const LOADING_DATA='LOADING_DATA'
export const GET_PRODUCTS='GET_PRODUCTS'
export const ADD_PRODUCTS='ADD_PRODUCTS'
export const REMOVE_PRODUCTS='REMOVE_PRODUCTS'
export const EDIT_PRODUCTS='EDIT_PRODUCTS'
export const LOADING_PRODUCTS='LOADING_PRODUCTS'
export const ERROR_PRODUCTS='ERROR_PRODUCTS'
export const ADD_REVIEWS='ADD_REVIEWS'
export const GET_REVIEWS='GET_REVIEWS'
export const LOADING_REVIEWS='LOADING_REVIEWS'
export const ERROR_REVIEWS='ERROR_REVIEWS'
export const REMOVE_REVIEWS='REMOVE_REVIEWS'
export const EDIT_REVIEWS='EDIT_REVIEWS'
export const ADD_CART='ADD_CART'
export const GET_CART='GET_CART'
export const ADD_SUBCATEGORY='ADD_SUBCATEGORY'
export const GET_SUBCATEGORY='GET_SUBCATEGORY'
export const REMOVE_SUBCATEGORY='REMOVE_SUBCATEGORY'
export const EDIT_SUBCATEGORY='EDIT_SUBCATEGORY'
export const ADD_CATEGORY='ADD_CATEGORY'
export const GET_CATEGORY='GET_CATEGORY'
export const REMOVE_CATEGORY='REMOVE_CATEGORY'
export const EDIT_CATEGORY='EDIT_CATEGORY'










